databases:
  - name: emart-db
    databaseName: emart
    user: emart
    plan: free

services:
  - type: web
    name: emart-api
    runtime: node
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: emart-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://ecommerce-roan-sigma.vercel.app
